### ISSUE TITLE
Proxy WTF???

### ISSUE THREAD

**Issue by MrCheater** [wavesoft/dot-dom#11]
http://caniuse.com/#feat=proxy
:-1:

**Comment by wavesoft** [comment]
Hey @MrCheater , as I clearly state in the `README.md` this library is exploiting the ES6 features in order to save space. Support of older browsers was never the intention, since the moment you do so, you loose the benefit of it's tiny size.

And by the way, it's not only Proxy
* [Rest parameters](http://caniuse.com/#feat=rest-parameters) is not fully there yet
* [Arrow functions](http://caniuse.com/#feat=arrow-functions) is not fully there yet

But why support older browsers since in less than a year most of the world will upgrade their browser?
