### ISSUE TITLE
Comparing minified size based on various tools

### ISSUE THREAD

**Issue by PascalPflaum** [wavesoft/dot-dom#17]
Hi.

I got aware of the project at the React.js HH Meetup.
Noticing you used babili, I asked myself, if you tested other compression tools, like uglify or closure.
Was there any particular reason for selecting babili?

I offer my help, if you haven't done this already before chosing babili.

**Comment by wavesoft** [comment]
Hello @PascalPflaum and thank you for your interest! I was looking for an ES6-aware minifier, since the code is never transpiled to ES5. From a quick search that I did, `babili` was the one that had this support, but honestly I din't do any extensive research on minifiers.

If you are interested, you are more than welcome to search for alternatives 😄  ✨

**Comment by PascalPflaum** [comment]
I created a PR that automatically build a js and a js.gz file for babili and uglifyJS2. The gulp task then picks the smallest file for uncompressed js and compressed js.gz

#28
